### ISSUE TITLE
Merge next branch into master

### ISSUE THREAD

**Issue by brendanzab** [pikelet-lang/pikelet#196]
I've just published the [`next` branch](https://github.com/pikelet-lang/pikelet/tree/next) and opened #197 which marks the beginning of my work to rebuild the current type checker on a better, more efficient, easier to understand foundation - ie. using [normalization by evaluation](https://en.wikipedia.org/wiki/Normalisation_by_evaluation). I've learned a huge amount since I implemented Pikelet originally, and this is the result of that!

Closes #14, #62, #109, #181.

## Todo

In order to get to a stage where we are on-par with our current implementation, I'll still need to do a number of things:

- [x] implement comments (using a custom lexer) (#199)
- [x] implement dependent record types
- [x] implement dependent function types (#200)
- [ ] implement let expressions
- [ ] type annotations on record terms
- [x] pretty print terms with the correct precedence (af71434e7ed45c3e35831ec959fab4e54d321299)
- [x] use a pretty error reporting library like [codespan](https://github.com/brendanzab/codespan) or [annotate-snippets](https://github.com/rust-lang/annotate-snippets-rs/)
- [ ] implement imports
- [x] clean up the documentation page
- [x] fix function eliminations

...I might come up with some other things though later on!
